### ISSUE TITLE
Document the OSV certifier

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/guac-docs#133]
How does GUAC pull from OSV? What is and is not supported? How is it invoked?

**Comment by abhirajadhikary06** [comment]
Hi! @funnelfiasco Can you assign me this issue under hacktober2024?

**Comment by abhirajadhikary06** [comment]
@funnelfiasco Can you review my [PR ](https://github.com/guacsec/guac-docs/pull/165)
