### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/guac-docs#136]
The `LICENSE` file in this repo contains the MIT license and says "Copyright (c) 2022 just-the-docs". The files in the `.github/` directory refer to the Apache Software License with copyright attributed to "The GUAC Authors". 

If this is intentional, we should document it. If it's unintentional, we should rectify it and make sure our attributions are correct.

**Comment by mihaimaruseac** [comment]
I think it's a mistake due to copy-paste, but let's discuss with the other maintainers too

**Comment by funnelfiasco** [comment]
Discussed in [today's Maintainer Meeting](https://github.com/guacsec/governance/blob/main/meetings/maintainers/2024/maintainers-2024-07-29.md) and the accepted solution is to:

* Keep the GitHub workflow files under ASL 2.0
* Specify that the code in this repo is licensed under MIT
* Specify that content in this repo is licensed under CC BY 4.0
