### ISSUE TITLE
Add CertifyLegal to demos

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/guac-docs#146]
Probably in known-and-unknown.md

**Comment by funnelfiasco** [comment]
This needs to happen after the next release, which will include the ClearlyDefined certifier in the demo compose file.

**Comment by robert-cronin** [comment]
I'd like to take this one on if no one else has started already, however I think there is a dependency here that's worth noting:

The `guacone query known` command is the main way the `known-and-unknown.md` demo explores different GUAC nodes, but it doesn't yet include `CertifyLegal` nodes to the best of my knowledge.

To properly document CertifyLegal in the docs, I've submitted a PR [here](https://github.com/guacsec/guac/pull/2254) that adds CertifyLegal support to the query known command first.
