### ISSUE TITLE
Document configuration settings

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/guac-docs#153]
Describe the values in [guac.yml](https://github.com/guacsec/guac/blob/main/guac.yaml) and how/why people may want to change them.

**Comment by iblameRishi** [comment]
Hey @funnelfiasco, I'd like to work on this please

**Comment by Atharva1723** [comment]
Can I work on this issue?

**Comment by funnelfiasco** [comment]
Welcome, both of you! If you have any questions, please join us in Slack or in our regular office hours. The [community page](https://guac.sh/community) has all of the details.

@iblameRishi since you were here first, go ahead. @Atharva1723, if there are other issues you'd like to work on, please do. If they're quick, you can just submit a PR without commenting on the issue first.

**Comment by neelshah2409** [comment]
Is anyone still working on this one or  I should take up ?
