### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by hayleycd** [guacsec/guac-docs#41]
Hi Guac team, 

I was reviewing a similar project and it occurred to me that the GUAC docs don't have google analytics incorporated into the project. It would be a couple of lines in the config file. 

[Here's how to add UA](https://just-the-docs.github.io/just-the-docs/docs/configuration/#google-analytics).

**Comment by funnelfiasco** [comment]
This was added in e1b118b (PR #66). Closing the issue!
