### ISSUE TITLE
IsDependency query missing fields

### ISSUE THREAD

**Issue by rmetzman** [guacsec/guac-docs#67]
The isDependency query should include origin and collector in order to receive relevant data back other than just the id.

page: https://docs.guac.sh/expanding-your-view/#step-7-examine-the-information-collected

**Comment by pxp928** [comment]
Hey @rmetzman, can you elaborate a bit more on this? The current query does include the origin and collector information. Here is the link to the GraphQL queries](https://github.com/guacsec/guac/blob/main/demo/workflow/queries.gql) shown in the example.

**Comment by rmetzman** [comment]
Okay, that makes sense.
