### ISSUE TITLE
Guac demo expected output differs from actual

### ISSUE THREAD

**Issue by mdeicas** [guacsec/guac-docs#95]
The second Guac demo  ["What is Known and Unknown about your Software Supply Chain](https://docs.guac.sh/known-and-unknown/) instructs the user to ingest an SBOM from `guac-data-main/top-dh-sboms/vault.json`. In Step 2, it asks the user to search for an artifact by hash ([here](https://github.com/guacsec/guac-docs/blob/a5ef6f6a39c1b5b8cc0c811db6e37e9aa80403ef/known-and-unknown.md?plain=1#L153)), but that hash is not present in the SBOM, and as a result the expected output does not appear. 

It seems that this hash is present in `guac-data-main/docs`, which the demo suggests to ingest in the [setup](https://docs.guac.sh/setup/) page, but not in the Known and Unknown demo.

**Comment by lumjjb** [comment]
hmmm since that part of it is asking for a SLSA attestation, i think i'd be more inclined to update step 1 to collect the docs as usual and skip the additional "vault.json" SBOM and query something within the docs corpus to avoid confusion. Thoughts @pxp928 @jeffmendoza ?

**Comment by pxp928** [comment]
> hmmm since that part of it is asking for a SLSA attestation, i think i'd be more inclined to update step 1 to collect the docs as usual and skip the additional "vault.json" SBOM and query something within the docs corpus to avoid confusion. Thoughts @pxp928 @jeffmendoza ?

One of the requirements for the ["What is Known and Unknown about your Software Supply Chain](https://docs.guac.sh/known-and-unknown/) is:

```
Completion of the [Expanding your view of the software supply chain demo](https://docs.guac.sh/expanding-your-view/)
```
where the vault data is ingested.

We could instead add to step 2 that ingest the "guac-data" if not already ingested before continuing

**Comment by pxp928** [comment]
created PR to address
